# Generated by Django 3.1.6 on 2021-02-19 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Schools',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sc_name', models.CharField(max_length=20, unique=True)),
                ('sc_max_st', models.IntegerField()),
                ('sc_address', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('st_first_name', models.CharField(max_length=20)),
                ('st_last_name', models.CharField(max_length=20)),
                ('st_ident', models.CharField(max_length=20, unique=True)),
                ('st_age', models.IntegerField()),
                ('st_class', models.CharField(max_length=10)),
                ('st_school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='school', to='student_api.schools')),
            ],
        ),
    ]
