# Generated by Django 3.1.6 on 2021-02-19 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schools',
            name='sc_address',
        ),
    ]
