# Generated by Django 3.1.6 on 2021-02-19 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_api', '0002_remove_schools_sc_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='schools',
            name='sc_address',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
