# Generated by Django 3.1.6 on 2021-02-19 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_api', '0004_auto_20210219_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='st_age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
